name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'


    - name: Set Git user name and email
      run: |
        git remote add origin https://'saikanth9010':'Sai@9059748363'@https://github.com/saikanth9010/will-you-be-my-girl-friend.git

        
    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install
        

    - name: Run Node.js code
      run: pnpm run deploy
